# Site settings
title: Lambda I/O Conf 2018
description: Brazil's first FP conference
baseurl: "https://lambda-io.github.io" # the subpath of your site, e.g. /blog
url: "https://lambda-io.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
event_name: Lambda I/O Conf 2018
event_description: Brazil's first functional programming conference
event_date: September 29, 2018
event_location: São Paulo, Brazil

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
